# site settings
title: Behrad Koohy
subtitle: PhD Researcher @ Southampton University
email: behrad.koohy@soton.ac.uk
description: I'm a PhD Student in Artificial Intelligence at the University of Southampton, and I am part of the Citizen-Centric Artificial Intelligence Systems research group. I primarily work on adaptive and intelligence transport systems, using techniques such as reinforcement learning and graph learning to progress towards the goal of making our cities healthier, more sustainable and prosperous. Outside of my research, I am also quite a keen hockey player.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Building 32
city: Southampton
state: Hampshire
zip_code: SO171BJ
country: United Kingdom of Great Britain and Northern Island
phone: (+44) 23 8059 5000

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/behradkoohy
  Instagram:
  LinkedIn: https://www.linkedin.com/in/behrad-koohy-58ab04169/
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
